### PR TITLE
force all datums as hex encoded strings

### PR DESCRIPTION
**Pull request by raymonstah**

### CODE REVIEW

**Comment by Quantumplation** [comment]
Can you elaborate on the motivation here?

**Comment by raymonstah** [comment]
> Can you elaborate on the motivation here?

Prior to v5.0.0, ogmios returns datums as hex encoded strings. Since then, datums are encoded as base64 strings. A lot of our newer code, specifically `scooper-rewards` already assume datums should be returned as hex strings. So this change forces all base64 encoded datum strings as _hex_  strings, so that we can continue reading from older ogmios versions without upgrading to v5.0+ until necessary.

**Comment by Quantumplation** [comment]
@raymonstah wouldn't it be the other way around then? If old versions report hex and new versions report base64; and we depend on hex, wouldn't this just *allow* us to upgrade without having to switch everything to reading base64? I don't see how it impacts us if we don't upgrade

**Review by Quantumplation — APPROVED** [review]

**Comment by raymonstah** [comment]
We could do it the other way around, but the newer code in sundae-scooper-rewards already assumes that it'll be receiving hex data.

**Pull request merged**
